version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: dev
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  # Maintain dependencies for maven
  - package-ecosystem: "maven" 
    directory: "/" 
    target-branch: dev
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "*maven-install-plugin*"
      # temporary deactivation of the maven-assembly-plugin update, because of the following issue: issues.apache.org/jira/browse/MASSEMBLY-1031
      - dependency-name: "*maven-assembly-plugin*"
