name: All checks pass

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  allchecks:
    runs-on: ubuntu-22.04
    steps:
      - uses: wechuli/allcheckspassed@v1
        with:
          retries: '15'
