name: Pull request

on:
  pull_request:

jobs:
  build-pr:
    if: contains(fromJson(vars.SUPPORTED_BRANCHES).all-branches, github.head_ref) != true
    uses: ./.github/workflows/_reusable_build.yml
    secrets: inherit
